import XCTest
@testable import ssshCrypto

/// Fixtures generated by OpenSSH 9.6's own `ssh-keygen`, and the expected
/// output checked by handing this writer's files back to `ssh-keygen -y`: it
/// reads them, derives the same public key, and — for the unencrypted ones —
/// the bytes are identical to what it wrote itself.
///
/// The encrypted fixture's ciphertext comes from an independent bcrypt_pbkdf
/// and AES-CTR (Python's `bcrypt` and `cryptography`), so matching it also
/// re-checks this package's own versions of both.
enum GeneratedKeyFixtures {
    static let ed25519Seed = bytes(
            "0bd2de3ba5f5f0977588ea9f7616bc735a5cc38b238a3216f02d5473cd0c9bac"
        )

    static let ed25519PublicKey = bytes(
            "56d4790e6667891db9a68d0ae96d37a4214415990bb95b93550cf61aeacd1884"
        )

    static let ed25519Comment = "oracle@test"
    static let ed25519CheckInt: UInt32 = 1092896851
    static let ed25519PublicLine = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFbUeQ5mZ4kduaaNCultN6QhRBWZC7lbk1UM9hrqzRiE oracle@test"

    /// Byte-identical to the file `ssh-keygen -t ed25519` produced.
    static let ed25519Plain = """
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
        QyNTUxOQAAACBW1HkOZmeJHbmmjQrpbTekIUQVmQu5W5NVDPYa6s0YhAAAAJBBJEhTQSRI
        UwAAAAtzc2gtZWQyNTUxOQAAACBW1HkOZmeJHbmmjQrpbTekIUQVmQu5W5NVDPYa6s0YhA
        AAAEAL0t47pfXwl3WI6p92FrxzWlzDiyOKMhbwLVRzzQybrFbUeQ5mZ4kduaaNCultN6Qh
        RBWZC7lbk1UM9hrqzRiEAAAAC29yYWNsZUB0ZXN0AQI=
        -----END OPENSSH PRIVATE KEY-----

        """

    /// Passphrase `hunter2`, salt `000102…0f`, 16 rounds.
    static let ed25519Encrypted = """
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABAAAQIDBA
        UGBwgJCgsMDQ4PAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIFbUeQ5mZ4kduaaN
        CultN6QhRBWZC7lbk1UM9hrqzRiEAAAAkNQ21gB2j5vOz8PttxbgxOwfCn/skrlLdHziCu
        jhl4cpMidjCC5RY50TBqbT6mn5NTWfNTdicb8fo/+HKojBP0kcNVrhfRmUp7W9boTHfhq7
        urFcH0Rcg1lNHkyrR07LurDfB64HtEGjFbJEEugTQaSFbwe5ObnD61egwibJL+Z65NUC58
        h3Yvn0jGNRj9KcRg==
        -----END OPENSSH PRIVATE KEY-----

        """

    static let rsaComment = "rsa@test"
    static let rsaCheckInt: UInt32 = 281220565
    static let rsaPublicLine = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC97ea+v+9DyB9NAMx1e22nPFcIPcCD/b+C//7HdnxXslmrw6R4FdCiWBgPvtElbX30LkMQhUg1hilaPVwU7qSprYVCfWyhBf7Ru/22/HXHnwwp4iPnc6NneMhEpjJxjoOjRIk/jFgMHGDXmlnePGIUrqPi15XiO9kYmgFIJoenZxy7UuIjYt+xc+1tCpYpO7fb8joo2mDRbY87P6IxzdlqQVxM0oW7W0uqMBHAlnC8wK/GeXqoNs/pc4jeKZB8oNNUaAmid1h90QfzZ2kFH3i2t4F2peo1JJiWMFXK0mnDcfpz5yUEXMuhEedkh7+eigLRiToB0c1aXMfL2zhizXFd rsa@test"

    static let rsaModulus = bytes(
            "00bdede6bebfef43c81f4d00cc757b6da73c57083dc083fdbf82fffec7767c57" +
            "b259abc3a47815d0a258180fbed1256d7df42e431085483586295a3d5c14eea4" +
            "a9ad85427d6ca105fed1bbfdb6fc75c79f0c29e223e773a36778c844a632718e" +
            "83a344893f8c580c1c60d79a59de3c6214aea3e2d795e23bd9189a01482687a7" +
            "671cbb52e22362dfb173ed6d0a96293bb7dbf23a28da60d16d8f3b3fa231cdd9" +
            "6a415c4cd285bb5b4baa3011c09670bcc0afc6797aa836cfe97388de29907ca0" +
            "d3546809a277587dd107f36769051f78b6b78176a5ea352498963055cad269c3" +
            "71fa73e725045ccba111e76487bf9e8a02d1893a01d1cd5a5cc7cbdb3862cd71" +
            "5d"
        )

    static let rsaPublicExponent = bytes("010001")

    static let rsaPrivateExponent = bytes(
            "06ab09a9c62cb69c66c4206df39ff70916292479a0f1fafa2e025572b1808b13" +
            "43d149ae39a6499efe4f62c08830a6b4c040d18b59a42caa7e7693e6b76b6b7a" +
            "c05dbb752c0adf9e4ff8282c80fc6134b1cbbb0c17dade96e3b43048d2ad288f" +
            "0b2fe382155b36673d0ec4c205911c266df06ad9ea351fa82f143b8049e136c3" +
            "392f15a9b39b02b872fe10391be71a6280ee25cc06d2e71379e7ad1a6583eabb" +
            "712bbcfd3f348e80b8e1d87bba1fd11458b93775099e9764a7c71fd1be8ea6fa" +
            "6dcec1bc165f484702bfec2accee652980b77a803815a3491f6c76e83fd73d5c" +
            "194c1173d1380701ebd451d37c962a054504f30e9d619e497fa4c321237af331"
        )

    static let rsaCoefficient = bytes(
            "2145029ba0df01f8bd063f6d0479fa3cf4b9d7dfa7c957f665e2805e0f797186" +
            "64c1cc896de9d3a318938340012fe115b48192a4aaa8401aec99f97648ac21ca" +
            "2da3d9072bbed8fc81fd69a30c39dc9e0741b7a5b4f2952adfc00b34f7865615" +
            "6a8756964a5f9d6dda3bea8eb7e1d109a064a83872eb9ab1ed5305b8ba1b8af2"
        )

    static let rsaPrime1 = bytes(
            "00eb0f90ad33f2f0bbf575d8b30ca88602c4042f89f8a9fdcd00078b2c3bd145" +
            "b0daf868f84dcf485f12352435f76901249c75cccf6c8708dfe319fafbb6513d" +
            "515371804678c058439c8a941ac2c2273d4824f045d638b7db7fd5f70610809e" +
            "7b40019032cf348c8165ccaee74748fc71cc9ce9fb9bfcc884f3e4ce4ee2523d" +
            "f9"
        )

    static let rsaPrime2 = bytes(
            "00ced922fe7cdee13bdd72f5dd7852a080164f94afe149c1f8f273b0ab79ac65" +
            "b0660c277a77cec72e20c1b5d613d3b21cb14f40a3c52842aa489dd6fd089958" +
            "0444fd4ec0dcdfe1d427fb5215b7778de67becc2ef511e15a033f5ff955ae269" +
            "bdadb600c105be77ce42367f0aa513dffc179a06d743d74df3293e72e4c888f7" +
            "85"
        )

    /// Byte-identical to the file `ssh-keygen -t rsa -b 2048` produced.
    static let rsaPlain = """
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
        NhAAAAAwEAAQAAAQEAve3mvr/vQ8gfTQDMdXttpzxXCD3Ag/2/gv/+x3Z8V7JZq8OkeBXQ
        olgYD77RJW199C5DEIVINYYpWj1cFO6kqa2FQn1soQX+0bv9tvx1x58MKeIj53OjZ3jIRK
        YycY6Do0SJP4xYDBxg15pZ3jxiFK6j4teV4jvZGJoBSCaHp2ccu1LiI2LfsXPtbQqWKTu3
        2/I6KNpg0W2POz+iMc3ZakFcTNKFu1tLqjARwJZwvMCvxnl6qDbP6XOI3imQfKDTVGgJon
        dYfdEH82dpBR94treBdqXqNSSYljBVytJpw3H6c+clBFzLoRHnZIe/nooC0Yk6AdHNWlzH
        y9s4Ys1xXQAAA8AQwxXVEMMV1QAAAAdzc2gtcnNhAAABAQC97ea+v+9DyB9NAMx1e22nPF
        cIPcCD/b+C//7HdnxXslmrw6R4FdCiWBgPvtElbX30LkMQhUg1hilaPVwU7qSprYVCfWyh
        Bf7Ru/22/HXHnwwp4iPnc6NneMhEpjJxjoOjRIk/jFgMHGDXmlnePGIUrqPi15XiO9kYmg
        FIJoenZxy7UuIjYt+xc+1tCpYpO7fb8joo2mDRbY87P6IxzdlqQVxM0oW7W0uqMBHAlnC8
        wK/GeXqoNs/pc4jeKZB8oNNUaAmid1h90QfzZ2kFH3i2t4F2peo1JJiWMFXK0mnDcfpz5y
        UEXMuhEedkh7+eigLRiToB0c1aXMfL2zhizXFdAAAAAwEAAQAAAQAGqwmpxiy2nGbEIG3z
        n/cJFikkeaDx+vouAlVysYCLE0PRSa45pkme/k9iwIgwprTAQNGLWaQsqn52k+a3a2t6wF
        27dSwK355P+CgsgPxhNLHLuwwX2t6W47QwSNKtKI8LL+OCFVs2Zz0OxMIFkRwmbfBq2eo1
        H6gvFDuASeE2wzkvFamzmwK4cv4QORvnGmKA7iXMBtLnE3nnrRplg+q7cSu8/T80joC44d
        h7uh/RFFi5N3UJnpdkp8cf0b6OpvptzsG8Fl9IRwK/7CrM7mUpgLd6gDgVo0kfbHboP9c9
        XBlMEXPROAcB69RR03yWKgVFBPMOnWGeSX+kwyEjevMxAAAAgCFFApug3wH4vQY/bQR5+j
        z0udffp8lX9mXigF4PeXGGZMHMiW3p06MYk4NAAS/hFbSBkqSqqEAa7Jn5dkisIcoto9kH
        K77Y/IH9aaMMOdyeB0G3pbTylSrfwAs094ZWFWqHVpZKX51t2jvqjrfh0QmgZKg4cuuase
        1TBbi6G4ryAAAAgQDrD5CtM/Lwu/V12LMMqIYCxAQvifip/c0AB4ssO9FFsNr4aPhNz0hf
        EjUkNfdpASScdczPbIcI3+MZ+vu2UT1RU3GARnjAWEOcipQawsInPUgk8EXWOLfbf9X3Bh
        CAnntAAZAyzzSMgWXMrudHSPxxzJzp+5v8yITz5M5O4lI9+QAAAIEAztki/nze4TvdcvXd
        eFKggBZPlK/hScH48nOwq3msZbBmDCd6d87HLiDBtdYT07IcsU9Ao8UoQqpIndb9CJlYBE
        T9TsDc3+HUJ/tSFbd3jeZ77MLvUR4VoDP1/5Va4mm9rbYAwQW+d85CNn8KpRPf/BeaBtdD
        103zKT5y5MiI94UAAAAIcnNhQHRlc3QBAgM=
        -----END OPENSSH PRIVATE KEY-----

        """

    static func bytes(_ hex: String) -> [UInt8] {
        stride(from: 0, to: hex.count, by: 2).map { offset in
            let start = hex.index(hex.startIndex, offsetBy: offset)
            return UInt8(hex[start..<hex.index(start, offsetBy: 2)], radix: 16)!
        }
    }
}
